### ISSUE TITLE
Use an example and minor fixes

### ISSUE THREAD

**Issue by RohanAlexander** [iJustinn/Toronto_Cycling_Network#4]
May I please use this as an example? If so, can you please fix two things?

1: @citeRohan has the wrong details - Hadley Wickham's. Either remove the cite from the main paper or fix the details in bibtex.

2: Can you please wrap package names in the bibtex file with double braces - {{}} - e.g. instead of:
title = {sf: Simple Features for R},
It should be:
title = {{sf: Simple Features for R}},

**Comment by iJustinn** [comment]
Yes of course! The two issues you mentioned were solved and pushed to the repo.
